version: '3.7'

services:
    node:
        image: "library/node:latest"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        expose:
            - "8081"
        command: "npm start"